theme: jekyll-theme-cayman

title:            Hello Aru
url:              http://love.balabiu.com
author:
    name:         GuoBaoWei
    email:        273814299@qq.com
    weibo:        http://weibo.com/273814299/
description:      "Hello World!"
